### ISSUE TITLE
allow private field in package.json for scoped modules published as npm private packages

### ISSUE THREAD

**Issue by gscott** [npm/public-api#14]
I was converting a module to use [npm private packages] (https://www.npmjs.com/npm/private-packages) under my new organization.   The existing package.json had the `"private": true` flag set.

If you attempt to publish a scoped module to an organization with the `"private": true` flag set npm will refuse it.    So I took the flag out, but stupidly forgot to update the package name to a scoped module, e.g., 

What I should have done   | What I did               | 
---------- | ------------- | ----------------- |
`"name": "@myorg/my-module"`          | `"name": "my-module"`

...and in a flash published my module to the entire planet.   And as you all so [good-naturedly point out] (http://blog.npmjs.org/post/101934969510/oh-no-i-accidentally-published-private-data-to), even with an unpublish, you can't really undo that mistake.

It may be a little too easy to inadvertently make a private package irrevocably public via a typo in the package.json.  It's my fault.  But would it make sense to allow the `"private": true` flag to work even when publishing a scoped, private package?   Or allow me to have a setting on my account that says, "Nothing I do should ever be allowed to the public registry."   Protect me from myself, at least just a little.

**Comment by seldo** [comment]
This is a tricky problem. The default for any scoped package is private, but if you forget to scope your package at all, the default remains public. Changing that default would break thousands upon thousands of existing npm tutorials, so we're not going to do that.

Setting a user-level privacy default is a good idea, though. I'll add it to the list.

**Comment by gscott** [comment]
@seldo I don't propose you change the default for non-scoped pages to private -- you're right, that would be a disaster -- just don't refuse to publish a scoped module to a private package if the private flag is true, which is what I *believe* you are doing now.

**Comment by seldo** [comment]
So, what "private" means is "npm will never publish this package". It's not a good semantic name for that behaviour anymore, because it predates the existence of private packages on the server, but that's what it has always meant, and workflows are built around that, so moving that cheese is risky.

We considered adding some *other* flag that means "never make public" (bikeshed whatever name you want for that key) but concluded that conflating permissions with package metadata was violating a separation of concerns.

**Comment by gscott** [comment]
Understood.   The user level privacy setting you mentioned earlier will help.
